[package]
name = "tuber"
version = "0.1.0"
authors = ["Quinn Shanahan <q.shanahan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "*"
serde = "*"
serde_derive = "*"
dotenv = "*"
